-- AlterTable
ALTER TABLE "services" 
ADD COLUMN IF NOT EXISTS "category" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "short_desc" TEXT,
ADD COLUMN IF NOT EXISTS "full_desc" TEXT,
ADD COLUMN IF NOT EXISTS "featured_image" TEXT,
ADD COLUMN IF NOT EXISTS "icon_name" VARCHAR(50) DEFAULT 'Sparkles',
ADD COLUMN IF NOT EXISTS "features" JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "inclusions" JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "packages" 
ADD COLUMN IF NOT EXISTS "tagline" TEXT,
ADD COLUMN IF NOT EXISTS "capacity" VARCHAR(100),
ADD COLUMN IF NOT EXISTS "original_price" DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS "is_popular" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS "ideal_for" TEXT,
ADD COLUMN IF NOT EXISTS "inclusions" JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "features" JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "services_included" JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP;
